### ISSUE TITLE
Migration to new AnonCreds object format

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-acapy-tools#35]
ACA-Py will eventually move a feature that is currently experimental to ready-for-use status: AnonCreds RS support. With this change, the migration strategy used in the wallet upgrade tool will require tweaks to migrate an Indy wallet to the new AnonCreds format.

Is this something we should worry about? It should be technically possible to upgrade using this tool as is and then use the upgrade endpoint @jamshale is working on in https://github.com/hyperledger/aries-cloudagent-python/pull/2922.

cc: @swcurran

**Comment by swcurran** [comment]
Per the discussion at the Aries Maintainer Call 2024.05.07 — anyone using a ACA-Py with the Indy Wallet must update to Askar before updating to the use of the AnonCreds RS library.  That is necessary because the upgrade from Indy to Askar requires bringing down ACA-Py entirely and doing an offline upgrade.  The upgrade from Askar CredX to AnonCreds RS does not require that, and can be done via an upgrade endpoint under the control of the each tenant controller.

I believe this is documented in the ACA-Py migration — we should confirm.  There is a PR with a migration document.

**Comment by dbluhm** [comment]
As discussed in the the ACA-Py maintainers meeting on May 7, 2024, upgrading from Indy to Askar + AnonCreds RS will not be the responsibility of this script.

Migrating from Indy to Askar required the ACA-Py instance to be spun down, migrated, and brought back up. The change from CredX to AnonCreds is intended to be done live so tenants can do it at their discretion. Therefore, to upgrade from Indy to using Askar + AnonCreds RS will consist of first migrating to Askar and then following up with using the upgrade endpoint from there.
